При возникновении паники Go приостанавливает выполнение
функции и начинает раскручивать стек (stack unwinding)
вызовов до тех пор, пока не завершит работу приложения
или не найдет функцию обработки паники recover()

// ==============================================

    Recover.
    --------
    
Recover полезен только внутри defer 
в противном случае recover() просто вернет nil
и больше не будет ни на что влиять.

// ==============================================

    Когда фунскция func вызывает panic()
    ------------------------------------

то происходит следующее:
    1. Останавливается выполнение func.
    2. Вызывается все ее внутренние defer функции,
        вплоть до верхнего уровня в исполняемой горутине.
    3. Программа заканчивает выполнение и выводит ошибку,
        включая значене аргументов panic.

        

